services:
  pixel-backup:
    build: .
    container_name: pixel_backup
    restart: unless-stopped
    volumes:
      - /immich:/immich # Must be parent of syncthing volume
      - ./configs:/app/configs
      - /etc/localtime:/etc/localtime:ro

  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    volumes:
      - /immich/syncthing:/immich/syncthing
      - syncthing_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8384:8384" # GUI
      - "22000:22000/tcp"
      - "22000:22000/udp"

volumes:
  syncthing_config:
