# Generated by Django 6.1.1 on 2026-09-19 13:37

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("files_count", models.PositiveIntegerField()),
                ("total_bytes", models.PositiveBigIntegerField()),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(unique=True)),
                ("source_dir", models.CharField()),
                (
                    "sync_cutoff_at",
                    models.DateTimeField(
                        default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                        help_text="Only sync files created on or after this date/time; earlier files are skipped.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SyncedFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.TextField(unique=True)),
                ("dest_path", models.TextField()),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("created_at_ns", models.BigIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="history.batch",
                    ),
                ),
                (
                    "user_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="history.userconfig"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="user_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="history.userconfig"
            ),
        ),
    ]
