# Generated by Django 6.1.1 on 2026-09-20 19:08

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("files_count", models.PositiveIntegerField(default=0)),
                ("total_bytes", models.PositiveBigIntegerField(default=0)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Batches",
            },
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(unique=True)),
                ("source_dir", models.CharField()),
                ("sync_order", models.PositiveSmallIntegerField(unique=True)),
                (
                    "sync_cutoff_at",
                    models.DateTimeField(
                        default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                        help_text="Only sync assets created on or after this date/time; earlier assets are skipped.",
                    ),
                ),
                ("last_timestamp_ns", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SyncedAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.TextField()),
                ("dest_path", models.TextField()),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("created_at_ns", models.BigIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="history.batch",
                    ),
                ),
                (
                    "user_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="history.userconfig"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="user_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="batches", to="history.userconfig"
            ),
        ),
    ]
