# Generated by Django 6.1.1 on 2026-09-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("syncthing_dir", models.CharField(default="")),
                ("phone_limit_gb", models.FloatField(default=19.0)),
                ("stop_threshold_mb", models.PositiveSmallIntegerField(default=5)),
                ("cron_schedule", models.CharField(default="0 0 * * *")),
                ("cron_timezone", models.CharField(default="UTC")),
                ("min_sleep_seconds", models.IntegerField(default=60)),
                ("discord_webhook_url", models.CharField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
