# Generated by Django 6.1.1 on 2026-09-28 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0003_userconfig_sync_cutoff_ns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="synced_at",
            new_name="last_synced_at",
        ),
    ]
