# Generated by Django 6.1.1 on 2026-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0003_userconfig_sync_cutoff_ns"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="resynced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
